/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: teachersmapd (https://sketchfab.com/teachersmapd)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chemistry-benzene-7fc04cef71174d93893db16e364768f5
title: Chemistry_Benzene
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes } = useGLTF("/chem_benz/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-0.05, 0.09, 0.3]}
            rotation={[0, 0, 2.11]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_5.geometry}
              material={nodes.Object_5.material}
            />
          </group>
          <group
            position={[-0.04, 0.06, 0.3]}
            rotation={[0, 0, 2.11]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_7.geometry}
              material={nodes.Object_7.material}
            />
          </group>
          <group position={[0.1, 0.06, 0.3]} scale={0}>
            <mesh
              geometry={nodes.Object_9.geometry}
              material={nodes.Object_9.material}
            />
          </group>
          <group
            position={[0.06, 0.08, 0.3]}
            rotation={[0, 0, 1.06]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_11.geometry}
              material={nodes.Object_11.material}
            />
          </group>
          <group
            position={[0.06, 0.08, 0.3]}
            rotation={[0, 0, 1.06]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_13.geometry}
              material={nodes.Object_13.material}
            />
          </group>
          <group position={[0.1, 0.06, 0.3]} scale={0}>
            <mesh
              geometry={nodes.Object_15.geometry}
              material={nodes.Object_15.material}
            />
          </group>
          <group
            position={[0.12, 0.07, 0.3]}
            rotation={[0, 0, -1.04]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_17.geometry}
              material={nodes.Object_17.material}
            />
          </group>
          <group position={[0.17, 0.1, 0.3]} scale={0}>
            <mesh
              geometry={nodes.Object_19.geometry}
              material={nodes.Object_19.material}
            />
          </group>
          <group position={[0.1, -0.06, 0.3]} scale={0}>
            <mesh
              geometry={nodes.Object_21.geometry}
              material={nodes.Object_21.material}
            />
          </group>
          <group
            position={[0.12, -0.07, 0.3]}
            rotation={[0, 0, -2.08]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_23.geometry}
              material={nodes.Object_23.material}
            />
          </group>
          <group position={[0.18, -0.1, 0.29]} scale={0}>
            <mesh
              geometry={nodes.Object_25.geometry}
              material={nodes.Object_25.material}
            />
          </group>
          <group position={[0.1, 0, 0.3]} scale={0}>
            <mesh
              geometry={nodes.Object_27.geometry}
              material={nodes.Object_27.material}
            />
          </group>
          <group
            position={[0.07, 0, 0.3]}
            rotation={[0, 0, -Math.PI]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_29.geometry}
              material={nodes.Object_29.material}
            />
          </group>
          <group
            position={[-0.12, 0.07, 0.3]}
            rotation={[0, 0, -2.08]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_31.geometry}
              material={nodes.Object_31.material}
            />
          </group>
          <group position={[-0.19, 0.11, 0.29]} scale={0}>
            <mesh
              geometry={nodes.Object_33.geometry}
              material={nodes.Object_33.material}
            />
          </group>
          <group position={[-0.11, 0.06, 0.3]} scale={0}>
            <mesh
              geometry={nodes.Object_35.geometry}
              material={nodes.Object_35.material}
            />
          </group>
          <group position={[-0.11, 0, 0.3]} scale={0}>
            <mesh
              geometry={nodes.Object_37.geometry}
              material={nodes.Object_37.material}
            />
          </group>
          <group position={[-0.11, -0.06, 0.3]} scale={0}>
            <mesh
              geometry={nodes.Object_39.geometry}
              material={nodes.Object_39.material}
            />
          </group>
          <group
            position={[-0.13, -0.07, 0.3]}
            rotation={[0, 0, -1.04]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_41.geometry}
              material={nodes.Object_41.material}
            />
          </group>
          <group position={[-0.18, -0.1, 0.31]} scale={0}>
            <mesh
              geometry={nodes.Object_43.geometry}
              material={nodes.Object_43.material}
            />
          </group>
          <group position={[0, 0.12, 0.3]} scale={0}>
            <mesh
              geometry={nodes.Object_45.geometry}
              material={nodes.Object_45.material}
            />
          </group>
          <group
            position={[0, 0.14, 0.3]}
            rotation={[0, 0, -Math.PI]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_47.geometry}
              material={nodes.Object_47.material}
            />
          </group>
          <group position={[0, 0.21, 0.3]} scale={0}>
            <mesh
              geometry={nodes.Object_49.geometry}
              material={nodes.Object_49.material}
            />
          </group>
          <group position={[0, -0.12, 0.3]} scale={0}>
            <mesh
              geometry={nodes.Object_51.geometry}
              material={nodes.Object_51.material}
            />
          </group>
          <group
            position={[0, -0.14, 0.3]}
            rotation={[0, 0, -Math.PI]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_53.geometry}
              material={nodes.Object_53.material}
            />
          </group>
          <group position={[0, -0.21, 0.3]} scale={0}>
            <mesh
              geometry={nodes.Object_55.geometry}
              material={nodes.Object_55.material}
            />
          </group>
          <group
            position={[-0.03, -0.11, 0.3]}
            rotation={[0, 0, 1.06]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_57.geometry}
              material={nodes.Object_57.material}
            />
          </group>
          <group
            position={[-0.04, -0.06, 0.3]}
            rotation={[0, 0, -2.08]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_59.geometry}
              material={nodes.Object_59.material}
            />
          </group>
          <group
            position={[0.05, -0.09, 0.3]}
            rotation={[0, 0, 2.11]}
            scale={[0, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_61.geometry}
              material={nodes.Object_61.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/chem_benz/scene.gltf");
