/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: majid_smago (https://sketchfab.com/majid_smago)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/model-atom-bohr-e260278661024d368c4345ccafeeb8bb
title: Model Atom Bohr
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/phy_bohr/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0}>
            <group position={[-14.06, 43.96, 162.76]} scale={[11.2, 32.49, 1]}>
              <mesh
                geometry={nodes.Object_6.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-17.76, -51.62, 205.47]}
              rotation={[0, 0, Math.PI]}
              scale={[10.87, 31.55, 1]}
            >
              <mesh
                geometry={nodes.Object_8.geometry}
                material={materials.material_1}
              />
            </group>
            <group
              position={[136.62, 77.6, 175.62]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[15.54, 45.1, 1]}
            >
              <mesh
                geometry={nodes.Object_10.geometry}
                material={materials.material_2}
              />
            </group>
            <group
              position={[127.51, -119.72, 175.24]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[15.54, 45.1, 1]}
            >
              <mesh
                geometry={nodes.Object_12.geometry}
                material={materials.material_3}
              />
            </group>
            <group position={[138.16, 0, 0]}>
              <group
                position={[-161.05, -15.09, 152.91]}
                rotation={[-2.61, -0.36, -0.06]}
                scale={[0.62, 0.62, 0.62]}
              >
                <mesh
                  geometry={nodes.Object_15.geometry}
                  material={materials.material_4}
                />
              </group>
              <group
                position={[-166.29, -25.16, 167.06]}
                rotation={[2.8, 0.34, 1.58]}
                scale={[0.62, 0.62, 0.62]}
              >
                <mesh
                  geometry={nodes.Object_17.geometry}
                  material={materials.material_5}
                />
              </group>
              <group
                position={[-167.32, -6.98, 173.18]}
                rotation={[3, -0.66, 0.05]}
                scale={[0.62, 0.62, 0.62]}
              >
                <mesh
                  geometry={nodes.Object_19.geometry}
                  material={materials.material_6}
                />
              </group>
              <group
                position={[-131.26, -10.5, 163.8]}
                rotation={[-0.31, -0.16, 3.07]}
                scale={[0.62, 0.62, 0.62]}
              >
                <mesh
                  geometry={nodes.Object_21.geometry}
                  material={materials.material_7}
                />
              </group>
              <group
                position={[-157.31, -2.2, 185.44]}
                rotation={[-1.91, 0.01, 1.23]}
                scale={[0.62, 0.62, 0.62]}
              >
                <mesh
                  geometry={nodes.Object_23.geometry}
                  material={materials.material_8}
                />
              </group>
              <group
                position={[-145.16, -3.47, 184.19]}
                rotation={[-0.64, -0.52, 2.88]}
                scale={[0.62, 0.62, 0.62]}
              >
                <mesh
                  geometry={nodes.Object_25.geometry}
                  material={nodes.Object_25.material}
                />
              </group>
              <group
                position={[-137.72, 7.43, 166.12]}
                rotation={[2.8, 0.34, 1.58]}
                scale={[0.62, 0.62, 0.62]}
              >
                <mesh
                  geometry={nodes.Object_27.geometry}
                  material={materials.material_10}
                />
              </group>
              <group
                position={[-166.66, 4.25, 156.51]}
                rotation={[2.8, 0.34, 1.58]}
                scale={[0.62, 0.62, 0.62]}
              >
                <mesh
                  geometry={nodes.Object_29.geometry}
                  material={materials.material_11}
                />
              </group>
              <group
                position={[-150.39, 12.86, 158.81]}
                rotation={[-0.96, -1.16, 2.49]}
                scale={[0.62, 0.62, 0.62]}
              >
                <mesh
                  geometry={nodes.Object_31.geometry}
                  material={nodes.Object_31.material}
                />
              </group>
              <group
                position={[-137.97, -22.58, 176.8]}
                rotation={[2.8, 0.34, 1.58]}
                scale={[0.62, 0.62, 0.62]}
              >
                <mesh
                  geometry={nodes.Object_33.geometry}
                  material={materials.material_12}
                />
              </group>
              <group
                position={[-145.71, -16.07, 150.38]}
                rotation={[1.11, 1.04, 2.82]}
                scale={[0.62, 0.62, 0.62]}
              >
                <mesh
                  geometry={nodes.Object_35.geometry}
                  material={materials.material_13}
                />
              </group>
              <group
                position={[-329.67, -44.99, 67.85]}
                rotation={[0, -0.04, 0]}
                scale={[0.41, 0.41, 0.41]}
              >
                <mesh
                  geometry={nodes.Object_37.geometry}
                  material={materials.material_14}
                />
              </group>
              <group
                position={[-43.47, -9.07, 162.62]}
                rotation={[-0.98, -0.14, 2.82]}
                scale={[0.34, 0.34, 0.34]}
              >
                <mesh
                  geometry={nodes.Object_39.geometry}
                  material={nodes.Object_39.material}
                />
              </group>
              <group
                position={[-258.74, -13.39, 153.33]}
                rotation={[-0.98, -0.14, 2.82]}
                scale={[0.34, 0.34, 0.34]}
              >
                <mesh
                  geometry={nodes.Object_41.geometry}
                  material={nodes.Object_41.material}
                />
              </group>
              <group
                position={[-244.08, -116.72, 151.43]}
                rotation={[-0.98, -0.14, 2.82]}
                scale={[0.34, 0.34, 0.34]}
              >
                <mesh
                  geometry={nodes.Object_43.geometry}
                  material={nodes.Object_43.material}
                />
              </group>
              <group
                position={[-58.94, -114.01, 159.73]}
                rotation={[-0.98, -0.14, 2.82]}
                scale={[0.34, 0.34, 0.34]}
              >
                <mesh
                  geometry={nodes.Object_45.geometry}
                  material={nodes.Object_45.material}
                />
              </group>
              <group
                position={[-143.09, 133.68, 157.86]}
                rotation={[-0.98, -0.14, 2.82]}
                scale={[0.34, 0.34, 0.34]}
              >
                <mesh
                  geometry={nodes.Object_47.geometry}
                  material={nodes.Object_47.material}
                />
              </group>
              <group
                position={[-395.17, -61.44, 32.96]}
                rotation={[0, -0.04, 0]}
                scale={0.57}
              >
                <mesh
                  geometry={nodes.Object_49.geometry}
                  material={materials.material_16}
                />
              </group>
              <group
                position={[107.84, 49.42, 53.29]}
                rotation={[0, -0.04, 0]}
                scale={[1.56, 1.56, 1.56]}
              >
                <group rotation={[0, 0, Math.PI]} scale={[0.37, 0.37, 0.37]}>
                  <mesh
                    geometry={nodes.Object_52.geometry}
                    material={materials.material_17}
                  />
                </group>
              </group>
              <group
                position={[34.63, 35.3, 82.57]}
                rotation={[0, -0.04, 0]}
                scale={[1.13, 1.13, 1.13]}
              >
                <group rotation={[0, 0, Math.PI]} scale={[0.37, 0.37, 0.37]}>
                  <mesh
                    geometry={nodes.Object_55.geometry}
                    material={materials.material_18}
                  />
                </group>
              </group>
            </group>
            <group position={[-11.86, 77.51, 159.47]}>
              <group position={[-23.99, -5.49, 7.5]}>
                <mesh
                  geometry={nodes.Object_58.geometry}
                  material={materials.material_19}
                />
              </group>
            </group>
            <group position={[-13.48, -80.08, 171.45]}>
              <group position={[-29.5, -5.49, 7.5]}>
                <mesh
                  geometry={nodes.Object_61.geometry}
                  material={materials.material_20}
                />
              </group>
            </group>
            <group position={[193.73, -123.19, 171.15]}>
              <group position={[-28.95, -5.81, 7.5]}>
                <mesh
                  geometry={nodes.Object_64.geometry}
                  material={materials.material_21}
                />
              </group>
            </group>
            <group position={[222.66, 74.47, 171.17]}>
              <group position={[-55.89, 4.69, 7.5]}>
                <mesh
                  geometry={nodes.Object_67.geometry}
                  material={materials.material_22}
                />
              </group>
              <group position={[-55.89, -16.31, 7.5]}>
                <mesh
                  geometry={nodes.Object_69.geometry}
                  material={materials.material_23}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/phy_bohr/scene.gltf");
