/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: nilsausta (https://sketchfab.com/nilsausta)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/a3c1edfdf088448ca67c6f0f47a5c370
title: Ühe juhtme magnetväli mõjutab teist juhet
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/phy_magnet/scene.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          name="sirgek2si_v"
          position={[7.1, 3.05, -0.02]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes.sirgek2si_v_0.geometry}
            material={materials.nahkjas}
          />
          <mesh
            geometry={nodes.sirgek2si_v_1.geometry}
            material={materials.kyyned}
          />
          <mesh
            geometry={nodes.sirgek2si_v_2.geometry}
            material={materials.nahajoon}
          />
        </group>
        <group
          position={[-0.15, 3.18, -0.21]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={14.8}
        >
          <mesh
            geometry={nodes.nurgik_0.geometry}
            material={nodes.nurgik_0.material}
          />
        </group>
        <group
          position={[-0.11, 3.18, 0.11]}
          rotation={[0, 1.57, 0]}
          scale={[1, 1, 1.58]}
        >
          <mesh
            geometry={nodes.vektor_suur_roheline_0.geometry}
            material={materials.roheline}
          />
        </group>
        <group
          position={[-0.17, 3.18, 0]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        >
          <mesh
            geometry={nodes.vektor_suur_sinine_0.geometry}
            material={nodes.vektor_suur_sinine_0.material}
          />
        </group>
        <group position={[-2.23, 3.18, 0]} rotation={[0, -1.57, 0]}>
          <mesh
            geometry={nodes.must_nool001_0.geometry}
            material={nodes.must_nool001_0.material}
          />
        </group>
        <group position={[-3.68, -1.97, 0.44]} rotation={[0, 1.57, 0]}>
          <mesh
            geometry={nodes.I1_double_0.geometry}
            material={nodes.I1_double_0.material}
          />
        </group>
        <group position={[-3.68, 2.58, 0.3]} rotation={[0, 1.57, 0]}>
          <mesh
            geometry={nodes.I2_double_0.geometry}
            material={nodes.I2_double_0.material}
          />
        </group>
        <group position={[-0.18, 5.75, 0.08]} rotation={[Math.PI, 1.57, 0]}>
          <mesh
            geometry={nodes.NS_double001_0.geometry}
            material={nodes.NS_double001_0.material}
          />
          <mesh
            geometry={nodes.NS_double001_1.geometry}
            material={nodes.NS_double001_1.material}
          />
          <mesh
            geometry={nodes.NS_double001_2.geometry}
            material={materials.punane}
          />
        </group>
        <group
          position={[-0.14, -0.44, -1.35]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
        >
          <mesh
            geometry={nodes.F12_double_0.geometry}
            material={nodes.F12_double_0.material}
          />
        </group>
        <group
          position={[-0.14, 3.68, -4.04]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
        >
          <mesh
            geometry={nodes.B1_double_0.geometry}
            material={nodes.B1_double_0.material}
          />
        </group>
        <group
          position={[0.01, 3.18, 0]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.21, 0.21, 2.09]}
        >
          <mesh
            geometry={nodes.silinder_0.geometry}
            material={nodes.silinder_0.material}
          />
        </group>
        <group position={[1.08, 7.26, 5.9]} rotation={[-0.62, -0.22, -2.94]} />
        <group position={[-2.23, -1.34, 0]} rotation={[0, -1.57, 0]}>
          <mesh
            geometry={nodes.must_nool001_0_1.geometry}
            material={nodes.must_nool001_0_1.material}
          />
        </group>
        <group
          position={[0.01, -1.33, 0]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.21, 0.21, 2.09]}
        >
          <mesh
            geometry={nodes.silinder001_0.geometry}
            material={nodes.silinder001_0.material}
          />
        </group>
        <group
          position={[-1.83, -2.84, 6.22]}
          rotation={[-0.62, -0.22, -2.94]}
        />
        <group scale={84.69}>
          <mesh
            geometry={nodes.valgekast_0.geometry}
            material={materials.valge}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/phy_magnet/scene.gltf");
