/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Breno_dAquino (https://sketchfab.com/breno_daquino)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/e93a8031d7e1486eae36f2074969f3cb
title: PWR Nuclear Reactor
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/phy_nuclearReactor/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.Color_002} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.Color_D04} />
        <mesh
          geometry={nodes.mesh_3.geometry}
          material={materials.Concrete_Brushed}
        />
        <mesh
          geometry={nodes.mesh_4.geometry}
          material={materials.Concrete_Gray}
        />
        <mesh
          geometry={nodes.mesh_5.geometry}
          material={materials.M_0135_DarkGray}
        />
        <mesh
          geometry={nodes.mesh_6.geometry}
          material={materials.Metal_Corrogated_Rust3}
        />
        <mesh
          geometry={nodes.mesh_7.geometry}
          material={materials.Metal_Rusted}
        />
        <mesh
          geometry={nodes.mesh_8.geometry}
          material={materials.Tile_Ceiling_Grid}
        />
        <mesh
          geometry={nodes.mesh_9.geometry}
          material={materials.Water_Pool}
        />
        <mesh
          geometry={nodes.mesh_10.geometry}
          material={materials.Water_Pool_Light2}
        />
        <mesh
          geometry={nodes.mesh_11.geometry}
          material={nodes.mesh_11.material}
        />
        <mesh
          geometry={nodes.mesh_12.geometry}
          material={nodes.mesh_12.material}
        />
        <mesh
          geometry={nodes.mesh_13.geometry}
          material={nodes.mesh_13.material}
        />
        <mesh
          geometry={nodes.mesh_14.geometry}
          material={nodes.mesh_14.material}
        />
        <mesh
          geometry={nodes.mesh_15.geometry}
          material={nodes.mesh_15.material}
        />
        <mesh
          geometry={nodes.mesh_16.geometry}
          material={nodes.mesh_16.material}
        />
        <mesh
          geometry={nodes.mesh_17.geometry}
          material={materials.Color_008}
        />
        <mesh geometry={nodes.mesh_18.geometry} material={materials.Color_2} />
        <mesh geometry={nodes.mesh_19.geometry} material={materials.Color_3} />
        <mesh
          geometry={nodes.mesh_20.geometry}
          material={materials.Color_A11}
        />
        <mesh
          geometry={nodes.mesh_21.geometry}
          material={nodes.mesh_21.material}
        />
        <mesh
          geometry={nodes.mesh_22.geometry}
          material={nodes.mesh_22.material}
        />
        <mesh
          geometry={nodes.mesh_23.geometry}
          material={nodes.mesh_23.material}
        />
        <mesh
          geometry={nodes.mesh_24.geometry}
          material={nodes.mesh_24.material}
        />
        <mesh
          geometry={nodes.mesh_25.geometry}
          material={materials.Color_H06}
        />
        <mesh
          geometry={nodes.mesh_26.geometry}
          material={materials.material_20}
        />
        <mesh geometry={nodes.mesh_27.geometry} material={materials.material} />
      </group>
    </group>
  );
}

useGLTF.preload("/phy_nuclearReactor/scene.gltf");
