/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: nilsausta (https://sketchfab.com/nilsausta)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/4f608da828ce44b294bfb6ad64941b18
title: Kolme vektori liitmine
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/phy_vector/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={84.69}>
          <mesh
            geometry={nodes.valgekast_0.geometry}
            material={materials.valge_taust}
          />
        </group>
        <group rotation={[-Math.PI, 0, 0]} scale={0.59}>
          <mesh
            geometry={nodes.hall_osake_0.geometry}
            material={nodes.hall_osake_0.material}
          />
          <mesh
            geometry={nodes.hall_osake_1.geometry}
            material={nodes.hall_osake_1.material}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0.75]}>
          <mesh
            geometry={nodes.vektor_suur_sinine_0.geometry}
            material={nodes.vektor_suur_sinine_0.material}
          />
        </group>
        <group position={[2.27, -3.5, 0.36]} rotation={[Math.PI / 2, -0.98, 0]}>
          <mesh geometry={nodes.F_0.geometry} material={nodes.F_0.material} />
        </group>
        <group position={[-4.46, 0.01, -3.19]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.F001_0.geometry}
            material={nodes.F001_0.material}
          />
        </group>
        <group position={[-3.74, 0.01, 2.76]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.F002_0.geometry}
            material={nodes.F002_0.material}
          />
        </group>
        <group position={[-0.16, 2.03, 0.76]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.F003_0.geometry}
            material={nodes.F003_0.material}
          />
        </group>
        <group position={[3.43, 0.01, -1.5]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.F006_0.geometry}
            material={nodes.F006_0.material}
          />
        </group>
        <group position={[0.66, 0.01, 1.75]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.F007_0.geometry}
            material={nodes.F007_0.material}
          />
        </group>
        <group position={[0, 0.02, 0]} rotation={[1.57, -0.99, 0]}>
          <mesh
            geometry={nodes.vektor_suur_sinine001_0.geometry}
            material={nodes.vektor_suur_sinine001_0.material}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, -0.47]}>
          <mesh
            geometry={nodes.vektor_suur_sinine003_0.geometry}
            material={nodes.vektor_suur_sinine003_0.material}
          />
        </group>
        <group
          position={[-3.56, 0, 1.82]}
          rotation={[-Math.PI, 0, 0]}
          scale={0.59}
        >
          <mesh
            geometry={nodes.hall_osake003_0.geometry}
            material={nodes.hall_osake003_0.material}
          />
          <mesh
            geometry={nodes.hall_osake003_1.geometry}
            material={nodes.hall_osake003_1.material}
          />
        </group>
        <group
          position={[-4.41, 0, -4.1]}
          rotation={[-Math.PI, 0, 0]}
          scale={0.59}
        >
          <mesh
            geometry={nodes.hall_osake002_0.geometry}
            material={nodes.hall_osake002_0.material}
          />
          <mesh
            geometry={nodes.hall_osake002_1.geometry}
            material={nodes.hall_osake002_1.material}
          />
        </group>
        <group
          position={[-0.01, 0.01, 0.01]}
          rotation={[-Math.PI, -0.46, -Math.PI]}
          scale={[0.13, 0.03, 0.03]}
        >
          <mesh
            geometry={nodes.Cube_0.geometry}
            material={nodes.Cube_0.material}
          />
        </group>
        <group
          position={[-0.01, 0.01, 0.01]}
          rotation={[-Math.PI, 0.77, -Math.PI]}
          scale={[0.13, 0.03, 0.03]}
        >
          <mesh
            geometry={nodes.Cube001_0.geometry}
            material={nodes.Cube001_0.material}
          />
        </group>
        <group position={[0.05, -8.2, -0.01]} scale={[0.13, 0.01, 0.03]}>
          <mesh
            geometry={nodes.Cube003_0.geometry}
            material={nodes.Cube003_0.material}
          />
        </group>
        <group
          position={[0, 2.02, -0.03]}
          rotation={[-Math.PI, 0, 0]}
          scale={0.59}
        >
          <mesh
            geometry={nodes.hall_osake003_0_1.geometry}
            material={nodes.hall_osake003_0_1.material}
          />
          <mesh
            geometry={nodes.hall_osake003_1_1.geometry}
            material={nodes.hall_osake003_1_1.material}
          />
        </group>
        <group position={[0, 0.02, 0]} rotation={[1.57, -Math.PI / 2, 0]}>
          <mesh
            geometry={nodes.vektor_suur_sinine002_0.geometry}
            material={nodes.vektor_suur_sinine002_0.material}
          />
        </group>
        <group position={[-0.16, 0.05, 0.76]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.F004_0.geometry}
            material={nodes.F004_0.material}
          />
          <mesh
            geometry={nodes.F004_1.geometry}
            material={materials["black_shadeless.001"]}
          />
        </group>
        <group
          position={[0, -3.82, 0.44]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        >
          <mesh
            geometry={nodes.F008_0.geometry}
            material={nodes.F008_0.material}
          />
        </group>
        <group
          position={[5.37, 0.03, -2.75]}
          rotation={[-0.32, 0, -1.57]}
          scale={[0.13, 0.01, 0.03]}
        >
          <mesh
            geometry={nodes.Cube002_0.geometry}
            material={nodes.Cube002_0.material}
          />
        </group>
        <group
          position={[2.95, 0.04, 2.71]}
          rotation={[0.29, 0.08, -1.3]}
          scale={[0.13, 0.01, 0.03]}
        >
          <mesh
            geometry={nodes.Cube004_0.geometry}
            material={nodes.Cube004_0.material}
          />
        </group>
        <group
          position={[0, 1.77, 0.01]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={[0.13, 0.03, 0.03]}
        >
          <mesh
            geometry={nodes.Cube005_0.geometry}
            material={nodes.Cube005_0.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/phy_vector/scene.gltf");
